# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-13 21:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20160513_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='current_status',
        ),
    ]
