# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('doc_file', models.FilePathField(verbose_name='../static/docs/')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
