# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-17 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docupload', '0004_auto_20161013_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='extension',
            field=models.CharField(default='docx', max_length=20),
        ),
    ]
