# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-23 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docupload', '0005_documentation_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='description',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='doc_file',
            field=models.FileField(upload_to='/home/lenovo/Desktop/oksp/media/'),
        ),
    ]
