# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-23 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docupload', '0006_auto_20161023_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
