# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-31 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('docupload', '0007_auto_20161023_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='doc_file',
            field=models.FileField(upload_to='/home/darknight/Desktop/oksp/media/'),
        ),
    ]
