# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 00:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docupload', '0006_auto_20160913_0346'),
        ('docupload', '0008_auto_20161031_2113'),
    ]

    operations = [
    ]
