# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-13 05:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('text', models.TextField()),
                ('comment_link',
                 models.ForeignKey(blank=True,
                                   null=True,
                                   on_delete=django.db.models.deletion.CASCADE,
                                   to='hacker_news.Comment')),
            ], ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('upvotes', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'News',
                'verbose_name': 'News',
            }, ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('nickname', models.CharField(max_length=24,
                                              unique=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('picture', models.ImageField(
                    blank=True, null=True, upload_to='')),
                ('cover', models.ImageField(
                    blank=True, null=True, upload_to='')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('google', models.URLField(blank=True, null=True)),
                ('blogger', models.URLField(blank=True, null=True)),
                ('homepage', models.URLField(blank=True, null=True)),
                ('behance', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='user_profile',
                    to=settings.AUTH_USER_MODEL)),
            ], ),
        migrations.AddField(model_name='comment',
                            name='link',
                            field=models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to='hacker_news.News'), ),
    ]
