# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-12 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacker_news', '0004_auto_20160514_0310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='vote',
            name='amount',
            field=models.IntegerField(choices=[(1, 1), (-1, -1), (0, 0)], default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(to='hacker_news.Tag'),
        ),
    ]
