# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 23:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hacker_news', '0005_auto_20160912_2008'),
        ('hacker_news', '0005_auto_20160913_0346'),
    ]

    operations = [
    ]
